import "../globals.css";

import Header from "../components/Header";
import type { Metadata } from "next";
import { ReactNode } from "react";
import TranslationsProvider from "../providers/TranslationsProvider";
import { dir } from "i18next";
import { i18nConfig } from "@/i18nConfig";
import initTranslations from "../i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  const { children } = props;

  if (!i18nConfig.locales.includes(locale)) {
    // notFound();
  }

  const i18nNamespaces = ["common", "header", "about"];
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={dir(locale)}>
      <body>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}
        >
          <Header />
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}
